[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.10"
tag_format = "v$version"
changelog_incremental = true
bump_message = "bump: version $current_version → $new_version [skip ci]"
